CREATE INDEX "booking_messages_booking_id_idx" ON "booking_messages" USING btree ("booking_id");--> statement-breakpoint
CREATE INDEX "booking_messages_sender_id_idx" ON "booking_messages" USING btree ("sender_id");--> statement-breakpoint
CREATE INDEX "booking_messages_is_read_idx" ON "booking_messages" USING btree ("is_read");--> statement-breakpoint
CREATE INDEX "booking_messages_created_at_idx" ON "booking_messages" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "booking_photos_booking_id_idx" ON "booking_photos" USING btree ("booking_id");--> statement-breakpoint
CREATE INDEX "booking_photos_photo_type_idx" ON "booking_photos" USING btree ("photo_type");--> statement-breakpoint
CREATE INDEX "booking_photos_uploaded_at_idx" ON "booking_photos" USING btree ("uploaded_at");--> statement-breakpoint
CREATE INDEX "bookings_guest_id_idx" ON "bookings" USING btree ("guest_id");--> statement-breakpoint
CREATE INDEX "bookings_property_id_idx" ON "bookings" USING btree ("property_id");--> statement-breakpoint
CREATE INDEX "bookings_status_idx" ON "bookings" USING btree ("status");--> statement-breakpoint
CREATE INDEX "bookings_check_in_date_idx" ON "bookings" USING btree ("check_in_date");--> statement-breakpoint
CREATE INDEX "bookings_check_out_date_idx" ON "bookings" USING btree ("check_out_date");--> statement-breakpoint
CREATE INDEX "bookings_created_at_idx" ON "bookings" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "delivery_orders_guest_id_idx" ON "delivery_orders" USING btree ("guest_id");--> statement-breakpoint
CREATE INDEX "delivery_orders_property_id_idx" ON "delivery_orders" USING btree ("property_id");--> statement-breakpoint
CREATE INDEX "delivery_orders_status_idx" ON "delivery_orders" USING btree ("status");--> statement-breakpoint
CREATE INDEX "delivery_orders_created_at_idx" ON "delivery_orders" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "messages_booking_id_idx" ON "messages" USING btree ("booking_id");--> statement-breakpoint
CREATE INDEX "messages_sender_id_idx" ON "messages" USING btree ("sender_id");--> statement-breakpoint
CREATE INDEX "messages_is_read_idx" ON "messages" USING btree ("is_read");--> statement-breakpoint
CREATE INDEX "messages_created_at_idx" ON "messages" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "properties_host_id_idx" ON "properties" USING btree ("host_id");--> statement-breakpoint
CREATE INDEX "properties_location_idx" ON "properties" USING btree ("location");--> statement-breakpoint
CREATE INDEX "properties_monthly_price_idx" ON "properties" USING btree ("monthly_price");--> statement-breakpoint
CREATE INDEX "properties_created_at_idx" ON "properties" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "property_access_info_property_id_idx" ON "property_access_info" USING btree ("property_id");--> statement-breakpoint
CREATE INDEX "reviews_booking_id_idx" ON "reviews" USING btree ("booking_id");--> statement-breakpoint
CREATE INDEX "reviews_property_id_idx" ON "reviews" USING btree ("property_id");--> statement-breakpoint
CREATE INDEX "reviews_guest_id_idx" ON "reviews" USING btree ("guest_id");--> statement-breakpoint
CREATE INDEX "reviews_created_at_idx" ON "reviews" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "users_email_idx" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "users_verification_token_idx" ON "users" USING btree ("verification_token");--> statement-breakpoint
CREATE INDEX "users_reset_password_token_idx" ON "users" USING btree ("reset_password_token");